

- name: instalando pacotes
  hosts: automation
  tasks:
   - name: executar este modulo somente na maquina que aplicar a var
     package:
      name: vim

   - name: criando usuario devops
     user:
      name: devops
      state: present
      password: '$1$3mZdJ6Io$94tP7Un5vtXWWyxnIjuB00'

   - name: criando usuario developer
     user:
      name: developer
      state: present
      password: '$1$3mZdJ6Io$94tP7Un5vtXWWyxnIjuB00'

   - name: criando usuario eduardo
     user:
      name: developer
      state: present
      password: '$1$3mZdJ6Io$94tP7Un5vtXWWyxnIjuB00'
